name: Frontend Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1 - Get Repository Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2 - Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3 - Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4 - Build Frontend Project
      - name: Build Project
        run: npm run build

      # Step 5 - Deploy Build Files to domene.no
      - name: Deploy to domene.no FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}

          # React/Vite build folder
          local-dir: ./build/

          # Hosting public folder
          server-dir: /public_html/

          # Prevent full folder cleanup
          dangerous-clean-slate: false

          # Ignore protected/system files
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .htaccess
            .well-known/**
